// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjajj27BYKX5O3x0S5PlS5yeaODJWfMmM',
    appId: '1:285077831674:web:36488829b6f4966576ee43',
    messagingSenderId: '285077831674',
    projectId: 'volleyballcenter-57da3',
    authDomain: 'volleyballcenter-57da3.firebaseapp.com',
    storageBucket: 'volleyballcenter-57da3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlR56_JzloutL5LKlVdd1NSH7iPLg0Nv8',
    appId: '1:285077831674:android:98826544c93b704b76ee43',
    messagingSenderId: '285077831674',
    projectId: 'volleyballcenter-57da3',
    storageBucket: 'volleyballcenter-57da3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrWL4fq2aZChhGDJglN8FJIEpLQs_3HMA',
    appId: '1:285077831674:ios:7366f2a215cfaf0e76ee43',
    messagingSenderId: '285077831674',
    projectId: 'volleyballcenter-57da3',
    storageBucket: 'volleyballcenter-57da3.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrWL4fq2aZChhGDJglN8FJIEpLQs_3HMA',
    appId: '1:285077831674:ios:7366f2a215cfaf0e76ee43',
    messagingSenderId: '285077831674',
    projectId: 'volleyballcenter-57da3',
    storageBucket: 'volleyballcenter-57da3.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjajj27BYKX5O3x0S5PlS5yeaODJWfMmM',
    appId: '1:285077831674:web:7caa404182565c7f76ee43',
    messagingSenderId: '285077831674',
    projectId: 'volleyballcenter-57da3',
    authDomain: 'volleyballcenter-57da3.firebaseapp.com',
    storageBucket: 'volleyballcenter-57da3.firebasestorage.app',
  );
}
